name: Docker Test

on:
  pull_request:
    types: [synchronize, opened]

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4

      - name: docker build
        run: |
          cd docker/ubuntu24-dotnet8-opencv4.12.0
          docker build -t shimat/ubuntu24-dotnet8-opencv4.12.0 .
